### ISSUE TITLE
mb_str_replace

### ISSUE THREAD

**Issue by salarmehr** [alecgorge/PHP-String-Class#2]
I think following is more efficient than current `mb_str_replace`

```
function mb_str_replace($search, $replace, $subject){
        return preg_replace('@'.preg_quote($search).'@u',$replace,$subject);
}
```

**Comment by alecgorge** [comment]
Fix made, thanks.

https://github.com/alecgorge/PHP-String-Class/commit/1cc8598a82a0f8e402db64b5810f8192b10bd77c

**Comment by alecgorge** [comment]
https://gist.github.com/alecgorge/5130170

**Comment by salarmehr** [comment]
Thanks for performance calculation.
